import { FC } from 'react';
import { Link } from 'wouter';
import { Button } from '@/components/ui/button';
import { 
  Card, 
  CardContent, 
  CardDescription, 
  CardHeader, 
  CardTitle 
} from '@/components/ui/card';
import { ArrowLeft } from 'lucide-react';

const TermsOfService: FC = () => {
  return (
    <div className="min-h-screen bg-neutral-50 py-12 px-4">
      <div className="container mx-auto max-w-4xl">
        <Card className="border-neutral-200">
          <CardHeader className="border-b pb-8">
            <Button variant="ghost" size="sm" asChild className="mb-6 -ml-2">
              <Link href="/">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to Home
              </Link>
            </Button>
            <CardTitle className="text-3xl">Terms of Service</CardTitle>
            <CardDescription>Last Updated: March 31, 2025</CardDescription>
          </CardHeader>
          <CardContent className="pt-8">
            <div className="prose max-w-none">
              <p>
                Welcome to Tekevwe, an AI-powered legal document assistant service. These Terms of Service ("Terms") govern your access to and use of our website, applications, and services (collectively, the "Service").
              </p>
              
              <p>
                By accessing or using our Service, you agree to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Service.
              </p>
              
              <h2>1. Account Registration</h2>
              
              <p>
                To use certain features of the Service, you may need to register for an account. When you register, you must provide accurate and complete information. You are solely responsible for maintaining the confidentiality of your account and password, and you accept responsibility for all activities that occur under your account.
              </p>
              
              <h2>2. User Categories</h2>
              
              <p>
                Our Service offers different account categories:
              </p>
              <ul>
                <li><strong>Student:</strong> For law students and legal education purposes</li>
                <li><strong>Individual:</strong> For personal legal assistance</li>
                <li><strong>Business:</strong> For companies and organizations</li>
              </ul>
              
              <h2>3. License to Use</h2>
              
              <p>
                Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, and revocable license to access and use the Service for your personal or internal business purposes.
              </p>
              
              <h2>4. Disclaimer of Legal Advice</h2>
              
              <p>
                <strong>The Service is not a substitute for the advice of a qualified lawyer.</strong> The information, documents, and content provided through the Service are for informational purposes only and do not constitute legal advice. The legal templates and documents generated by our Service are general in nature and may not be suitable for your specific situation.
              </p>
              
              <p>
                We recommend consulting with a qualified legal professional before taking any legal action or relying on documents generated through our Service.
              </p>
              
              <h2>5. User Obligations</h2>
              
              <p>You agree not to:</p>
              <ul>
                <li>Use the Service for any illegal purpose or in violation of any local, provincial, or federal law</li>
                <li>Violate or infringe other people's intellectual property, privacy, or other rights</li>
                <li>Interfere with or disrupt the Service or servers or networks connected to the Service</li>
                <li>Attempt to gain unauthorized access to any portion of the Service</li>
                <li>Use any robot, spider, or other automated device to access the Service</li>
                <li>Impersonate any person or entity or falsely state or misrepresent your affiliation with a person or entity</li>
              </ul>
              
              <h2>6. Intellectual Property</h2>
              
              <p>
                The Service and its contents, features, and functionality are owned by Tekevwe and are protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, sell, or lease any part of our Service without our prior written consent.
              </p>
              
              <h2>7. User Content</h2>
              
              <p>
                You retain all rights to any content you submit, post, or display on or through the Service ("User Content"). By providing User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, adapt, publish, and display such User Content in connection with providing and improving the Service.
              </p>
              
              <h2>8. Privacy</h2>
              
              <p>
                Your use of the Service is also subject to our Privacy Policy, which describes how we collect, use, and share your information.
              </p>
              
              <h2>9. Termination</h2>
              
              <p>
                We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason, including if you breach these Terms. Upon termination, your right to use the Service will immediately cease.
              </p>
              
              <h2>10. Changes to Terms</h2>
              
              <p>
                We may modify these Terms at any time. We will provide notice of material changes by posting the updated Terms on our website with a new effective date. Your continued use of the Service after any changes indicates your acceptance of the modified Terms.
              </p>
              
              <h2>11. Limitation of Liability</h2>
              
              <p>
                To the maximum extent permitted by law, in no event shall Tekevwe be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>
              
              <h2>12. Governing Law</h2>
              
              <p>
                These Terms shall be governed by and construed in accordance with the laws of Canada, without regard to its conflict of law provisions.
              </p>
              
              <h2>13. Contact Us</h2>
              
              <p>
                If you have any questions about these Terms, please contact us at:
              </p>
              
              <p>
                <a href="mailto:efe.obukohwo@outlook.com" className="text-primary hover:underline">
                  efe.obukohwo@outlook.com
                </a>
              </p>
              
              <hr className="my-8" />
              
              <div className="text-center">
                <p className="mb-6">
                  By using our Service, you acknowledge that you have read and understand these Terms of Service.
                </p>
                
                <Button asChild className="mx-auto">
                  <Link href="/">Return to Home</Link>
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default TermsOfService;